---
- name: Set up Git.
  hosts: picloud
  gather_facts: false
  become: true

  tasks:
    - name: Ensure git is installed
      ansible.builtin.apt:
        name: git
        state: present

    - name: Setup editor
      community.general.git_config:
        name: core.editor
        scope: system
        value: nano
