---
- name: Playbook for rebooting the RPis
  hosts: picloud
  serial: 10
  gather_facts: false
  become: true

  tasks:
    - name: Reboot RPi and wait for it to return
      ansible.builtin.reboot:
        reboot_timeout: 300
