---
- name: Playbook for rebooting the RPis
  hosts: picloud
  gather_facts: true
  tasks:
    - name: 'Reboot RPi'
      shell: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
      become: true

