---
- name: Playbook for restarting the PiNode MQTT Scripts
  hosts: picloud
  gather_facts: true
  tasks:
    - name: Restart Supervisor
      become: true
      ansible.builtin.command:
        cmd: systemctl restart supervisor

    - name: Wait supervisor to restart
      pause:
        seconds: 5

    - name: Check supervisor status of script
      command: supervisorctl status picloud-node-mqtt
      register: supervisor_statu
      become: true
