---
- name: Playbook for shutting down the RPis
  hosts: picloud
  serial: 10
  gather_facts: false
  become: true

  tasks:
    - name: Shutdown RPi
      ansible.builtin.command: shutdown -h now
      async: 1
      poll: 0
      ignore_errors: true
