name: Create and publish a Docker image to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'website/**'
      - '.github/workflows/docker-publish.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/ucl-casa-ce/picloud:latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Log in to the Container registry
        uses: docker/login-action@latest
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --file website/Dockerfile --tag ${{ env.IMAGE_NAME }} website
          docker push ${{ env.IMAGE_NAME }}

